// resources/js/Pages/Dashboard/Reports/Index.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { Head, router } from '@inertiajs/vue3';
import DashboardLayout from '@/Layouts/DashboardLayout.vue';
import ReportsTable from '@/components/admin/reports/ReportsTable.vue';
import { 
    Card, 
    CardContent, 
    CardHeader, 
    CardTitle, 
    CardDescription,
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue
} from '@/components/ui';
import type { AdminReport, Pagination } from '@/types';

interface Props {
    reports: {
        data: AdminReport[];
        links: any[];
    } & Pagination;
    filters: {
        status?: string;
        type?: string;
        per_page?: number;
    };
}

const props = defineProps<Props>();

const statusFilter = ref(props.filters.status || 'all');
const typeFilter = ref(props.filters.type || 'all');

const updateUrl = (updates: Record<string, any>) => {
    router.get(route('dashboard.reports'), {
        ...props.filters,
        ...updates,
    }, {
        preserveState: true,
        preserveScroll: true,
        replace: true
    });
};

watch(statusFilter, (val) => {
    updateUrl({ status: val === 'all' ? null : val, page: 1 });
});

watch(typeFilter, (val) => {
    updateUrl({ type: val === 'all' ? null : val, page: 1 });
});

const handlePageChange = (page: number) => {
    updateUrl({ page });
};

const handlePerPageChange = (perPage: number) => {
    updateUrl({ per_page: perPage, page: 1 });
};
</script>

<template>
    <Head title="إدارة البلاغات" />

    <DashboardLayout>
        <div class="space-y-6">
            <div>
                <h1 class="text-3xl font-bold tracking-tight">إدارة البلاغات</h1>
                <p class="text-muted-foreground">مراجعة وإدارة بلاغات المستخدمين</p>
            </div>

            <Card>
                <CardHeader>
                    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                        <div>
                            <CardTitle>البلاغات</CardTitle>
                            <CardDescription>عرض {{ reports.total }} بلاغ</CardDescription>
                        </div>
                        <div class="flex flex-wrap gap-2 w-full sm:w-auto">
                            <Select v-model="statusFilter">
                                <SelectTrigger class="w-full sm:w-[180px]">
                                    <SelectValue placeholder="تصفية حسب الحالة" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="all">كل الحالات</SelectItem>
                                    <SelectItem value="pending">قيد المراجعة</SelectItem>
                                    <SelectItem value="fixed">تم الحل</SelectItem>
                                    <SelectItem value="rejected">مرفوض</SelectItem>
                                </SelectContent>
                            </Select>

                            <Select v-model="typeFilter">
                                <SelectTrigger class="w-full sm:w-[180px]">
                                    <SelectValue placeholder="تصفية حسب النوع" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="all">كل الأنواع</SelectItem>
                                    <SelectItem value="content_issue">مشكلة محتوى</SelectItem>
                                    <SelectItem value="feedback">اقتراح / تعليق</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </div>
                </CardHeader>
                <CardContent>
                    <ReportsTable
                        :reports="reports.data"
                        :pagination="reports"
                        @page-change="handlePageChange"
                        @per-page-change="handlePerPageChange"
                    />
                </CardContent>
            </Card>
        </div>
    </DashboardLayout>
</template>

// frontend/src/app/dashboard/reports/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/lib/auth-context";
import { api } from "@/lib/api";
import { ReportsTable } from "@/components/admin/reports/ReportsTable";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";

export default function AdminReportsPage() {
    const { token, user } = useAuth();
    const isAdmin = user?.role === 'admin' || user?.role === 'moderator';

    // State
    const [reports, setReports] = useState([]);
    const [pagination, setPagination] = useState({
        current_page: 1,
        last_page: 1,
        per_page: 15,
        total: 0,
    });
    const [loading, setLoading] = useState(true);
    const [statusFilter, setStatusFilter] = useState("all");
    const [typeFilter, setTypeFilter] = useState("all");

    // Fetch reports
    const fetchReports = async (page = 1) => {
        if (!token || !isAdmin) return;
        setLoading(true);
        try {
            const params: any = { page };
            if (statusFilter !== "all") params.status = statusFilter;
            if (typeFilter !== "all") params.type = typeFilter;

            const response: any = await api.admin.getReports(token, params);
            setReports(response.data);
            setPagination({
                current_page: response.current_page,
                last_page: response.last_page,
                per_page: response.per_page,
                total: response.total,
            });
        } catch (error) {
            console.error("Failed to fetch reports:", error);
            // @ts-ignore
            toast.error(error.message || "فشل تحميل البلاغات");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        if (token && isAdmin) {
            fetchReports(1);
        }
    }, [token, isAdmin, statusFilter, typeFilter]);

    if (!isAdmin) {
        return <div className="p-8 text-center text-muted-foreground">غير مصرح لك بالوصول لهذه الصفحة</div>;
    }

    return (
        <div className="p-6 space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">إدارة البلاغات</h1>
                    <p className="text-muted-foreground">مراجعة وإدارة بلاغات المستخدمين</p>
                </div>
            </div>

            <Card>
                <CardHeader>
                    <div className="flex justify-between items-center">
                        <div>
                            <CardTitle>البلاغات</CardTitle>
                            <CardDescription>عرض {pagination.total} بلاغ</CardDescription>
                        </div>
                        <div className="flex gap-2">
                            <Select value={statusFilter} onValueChange={setStatusFilter}>
                                <SelectTrigger className="w-[180px]">
                                    <SelectValue placeholder="تصفية حسب الحالة" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="all">كل الحالات</SelectItem>
                                    <SelectItem value="pending">قيد المراجعة</SelectItem>
                                    <SelectItem value="fixed">تم الحل</SelectItem>
                                    <SelectItem value="rejected">مرفوض</SelectItem>
                                </SelectContent>
                            </Select>

                            <Select value={typeFilter} onValueChange={setTypeFilter}>
                                <SelectTrigger className="w-[180px]">
                                    <SelectValue placeholder="تصفية حسب النوع" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="all">كل الأنواع</SelectItem>
                                    <SelectItem value="content_issue">مشكلة محتوى</SelectItem>
                                    <SelectItem value="feedback">اقتراح / تعليق</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </div>
                </CardHeader>
                <CardContent>
                    <ReportsTable
                        reports={reports}
                        pagination={pagination}
                        onPageChange={(p) => fetchReports(p)}
                        onUpdate={() => fetchReports(pagination.current_page)}
                        loading={loading}
                    />
                </CardContent>
            </Card>
        </div>
    );
}
