// frontend/src/components/admin/UnifiedTagTable.tsx
'use client';

import { useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { api } from '@/lib/api';
import { Pagination } from '@/types';
import { Button } from '@/components/ui/button';
import { PaginationControls } from '@/components/ui/PaginationControls';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import { MoreHorizontal, Trash, Edit, Plus } from 'lucide-react';

interface Tag {
    id: number;
    name: string;
    recipes_count: number;
}

interface UnifiedTagTableProps {
    tags: Tag[];
    onUpdate: () => void;
    pagination: Pagination;
    onPageChange: (page: number) => void;
    onPerPageChange: (perPage: number) => void;
    loading: boolean;
    sortColumn: string;
    sortDirection: 'asc' | 'desc';
    onSort: (column: string) => void;
}

export function UnifiedTagTable({
    tags,
    onUpdate,
    pagination,
    onPageChange,
    onPerPageChange,
    loading,
    sortColumn,
    sortDirection,
    onSort
}: UnifiedTagTableProps) {
    const { token } = useAuth();
    const [selectedIds, setSelectedIds] = useState<number[]>([]);

    // Dialog states
    const [isDialogOpen, setIsDialogOpen] = useState(false);
    const [selectedTag, setSelectedTag] = useState<Tag | null>(null);
    const [isLoading, setIsLoading] = useState(false);

    // Form state
    const [name, setName] = useState('');

    const handleSelectAll = (checked: boolean) => {
        if (checked) {
            setSelectedIds(tags.map(t => t.id));
        } else {
            setSelectedIds([]);
        }
    };

    const handleSelectOne = (id: number, checked: boolean) => {
        if (checked) {
            setSelectedIds(prev => [...prev, id]);
        } else {
            setSelectedIds(prev => prev.filter(selectedId => selectedId !== id));
        }
    };

    const resetForm = () => {
        setName('');
        setSelectedTag(null);
    };

    const handleOpenCreate = () => {
        resetForm();
        setIsDialogOpen(true);
    };

    const handleOpenEdit = (tag: Tag) => {
        setSelectedTag(tag);
        setName(tag.name);
        setIsDialogOpen(true);
    };

    const handleSubmit = async () => {
        if (!token || !name.trim()) return;
        setIsLoading(true);
        try {
            if (selectedTag) {
                await api.admin.updateTag(token, selectedTag.id, name);
                toast.success('تم تحديث الوسم');
            } else {
                await api.admin.createTag(token, name);
                toast.success('تم إنشاء الوسم');
            }
            setIsDialogOpen(false);
            resetForm();
            onUpdate();
        } catch (error: any) {
            toast.error(error.message || 'فشل العملية');
        } finally {
            setIsLoading(false);
        }
    };

    const handleBulkDelete = async () => {
        if (!token || selectedIds.length === 0) return;
        if (!confirm(`هل أنت متأكد من حذف ${selectedIds.length} شارة؟ سيتم إزالتها من الوصفات المرتبطة.`)) return;

        setIsLoading(true);
        try {
            await api.admin.bulkTagActions(token, selectedIds);
            toast.success('تم حذف الوسوم');
            setSelectedIds([]);
            onUpdate();
        } catch (error: any) {
            toast.error(error.message || 'فشل الحذف الجماعي');
        } finally {
            setIsLoading(false);
        }
    };

    const handleDeleteSingle = async (tag: Tag) => {
        if (!token) return;
        if (!confirm(`هل أنت متأكد من حذف ${tag.name}؟ سيتم إزالته من الوصفات المرتبطة.`)) return;

        setIsLoading(true);
        try {
            await api.admin.deleteTag(token, tag.id);
            toast.success('تم حذف الوسم');
            onUpdate();
        } catch (error: any) {
            toast.error(error.message || 'فشل الحذف');
        } finally {
            setIsLoading(false);
        }
    };


    if (loading) return <div className="text-center py-8">جاري التحميل...</div>;

    return (
        <div>
            <div className="flex justify-between items-center mb-4">
                {selectedIds.length > 0 ? (
                    <div className="bg-muted px-4 py-2 rounded-lg flex items-center gap-4">
                        <span className="font-medium text-sm">تم تحديد {selectedIds.length}</span>
                        <Button size="sm" variant="destructive" onClick={handleBulkDelete} disabled={isLoading}>
                            <Trash className="w-4 h-4 mr-1" /> حذف المحدد
                        </Button>
                    </div>
                ) : (
                    <div></div> // Spacer
                )}
                <Button onClick={handleOpenCreate}>
                    <Plus className="w-4 h-4 mr-1" /> إضافة وسم
                </Button>
            </div>

            <div className="rounded-md border">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead className="w-12">
                                <Checkbox
                                    checked={tags.length > 0 && selectedIds.length === tags.length}
                                    onCheckedChange={(c) => handleSelectAll(!!c)}
                                />
                            </TableHead>
                            <TableHead className="cursor-pointer" onClick={() => onSort('name')}>
                                الاسم {sortColumn === 'name' && (sortDirection === 'asc' ? '↑' : '↓')}
                            </TableHead>
                            <TableHead className="cursor-pointer" onClick={() => onSort('recipes_count')}>
                                عدد الوصفات {sortColumn === 'recipes_count' && (sortDirection === 'asc' ? '↑' : '↓')}
                            </TableHead>
                            <TableHead>الإجراءات</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {tags.length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={4} className="text-center py-8 text-muted-foreground">
                                    لا توجد وسوم
                                </TableCell>
                            </TableRow>
                        ) : (
                            tags.map((tag) => (
                                <TableRow key={tag.id}>
                                    <TableCell>
                                        <Checkbox
                                            checked={selectedIds.includes(tag.id)}
                                            onCheckedChange={(c) => handleSelectOne(tag.id, !!c)}
                                        />
                                    </TableCell>
                                    <TableCell className="font-medium">
                                        {tag.name}
                                    </TableCell>
                                    <TableCell>
                                        {tag.recipes_count}
                                    </TableCell>
                                    <TableCell>
                                        <DropdownMenu>
                                            <DropdownMenuTrigger asChild>
                                                <Button variant="ghost" size="icon">
                                                    <MoreHorizontal className="h-4 w-4" />
                                                </Button>
                                            </DropdownMenuTrigger>
                                            <DropdownMenuContent align="end">
                                                <DropdownMenuItem onClick={() => handleOpenEdit(tag)}>
                                                    <Edit className="h-4 w-4" /> تعديل
                                                </DropdownMenuItem>
                                                <DropdownMenuItem onClick={() => handleDeleteSingle(tag)} className="text-red-600">
                                                    <Trash className="h-4 w-4" /> حذف
                                                </DropdownMenuItem>
                                            </DropdownMenuContent>
                                        </DropdownMenu>
                                    </TableCell>
                                </TableRow>
                            ))
                        )}
                    </TableBody>
                </Table>
            </div>

            <PaginationControls
                currentPage={pagination.current_page}
                totalPages={pagination.last_page}
                perPage={pagination.per_page}
                totalItems={pagination.total}
                onPageChange={onPageChange}
                onPerPageChange={onPerPageChange}
            />

            {/* Create/Edit Dialog */}
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>{selectedTag ? 'تعديل وسم' : 'إضافة وسم جديد'}</DialogTitle>
                        <DialogDescription>
                            {selectedTag ? 'تعديل اسم الوسم' : 'ادخل اسم الوسم الجديد'}
                        </DialogDescription>
                    </DialogHeader>
                    <div className="py-4">
                        <div className="space-y-2">
                            <label className="text-sm font-medium">اسم الوسم</label>
                            <Input
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                placeholder="مثال: نباتي"
                            />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
                            إلغاء
                        </Button>
                        <Button onClick={handleSubmit} disabled={!name.trim() || isLoading}>
                            {selectedTag ? 'حفظ التعديلات' : 'إنشاء'}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    );
}

// resources/js/components/admin/UnifiedTagTable.vue
<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@inertiajs/vue3';
import { 
    Button, 
    Checkbox, 
    Table, 
    TableBody, 
    TableCell, 
    TableHead, 
    TableHeader, 
    TableRow,
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    Input,
    PaginationControls
} from '@/components/ui';
import { MoreHorizontal, Trash, Edit, Plus } from 'lucide-vue-next';
import { toast } from 'vue-sonner';
import type { Tag, Pagination } from '@/types';

interface Props {
    tags: Tag[];
    pagination: Pagination;
    loading?: boolean;
    sortColumn: string;
    sortDirection: 'asc' | 'desc';
}

const props = defineProps<Props>();

const emits = defineEmits<{
    (e: 'sort', column: string): void;
    (e: 'pageChange', page: number): void;
    (e: 'perPageChange', perPage: number): void;
}>();

const selectedIds = ref<number[]>([]);
const isDialogOpen = ref(false);
const selectedTag = ref<Tag | null>(null);
const isLoading = ref(false);

const name = ref('');

const handleSelectAll = (checked: boolean) => {
    if (checked) {
        selectedIds.value = props.tags.map(t => t.id);
    } else {
        selectedIds.value = [];
    }
};

const handleSelectOne = (id: number, checked: boolean) => {
    if (checked) {
        selectedIds.value.push(id);
    } else {
        selectedIds.value = selectedIds.value.filter(selectedId => selectedId !== id);
    }
};

const resetForm = () => {
    name.value = '';
    selectedTag.value = null;
};

const handleOpenCreate = () => {
    resetForm();
    isDialogOpen.value = true;
};

const handleOpenEdit = (tag: Tag) => {
    selectedTag.value = tag;
    name.value = tag.name;
    isDialogOpen.value = true;
};

const handleSubmit = () => {
    if (!name.value.trim()) return;
    
    isLoading.value = true;
    const url = selectedTag.value 
        ? route('dashboard.tags.update', selectedTag.value.id) 
        : route('dashboard.tags.store');
    
    router.post(url, {
        _method: selectedTag.value ? 'PUT' : 'POST',
        name: name.value
    }, {
        onSuccess: () => {
            isDialogOpen.value = false;
            resetForm();
            toast.success(selectedTag.value ? 'تم تحديث الوسم' : 'تم إنشاء الوسم');
        },
        onError: () => {
            toast.error('فشل في حفظ الوسم');
        },
        onFinish: () => {
            isLoading.value = false;
        }
    });
};

const handleBulkDelete = () => {
    if (selectedIds.value.length === 0) return;
    if (!confirm(`هل أنت متأكد من حذف ${selectedIds.value.length} وسم؟ سيتم إزالتها من الوصفات المرتبطة.`)) return;

    isLoading.value = true;
    router.post(route('dashboard.tags.bulk'), {
        _method: 'PUT',
        ids: selectedIds.value,
        action: 'delete'
    }, {
        onSuccess: () => {
            selectedIds.value = [];
            toast.success('تم حذف الوسوم المحددة');
        },
        onError: () => {
            toast.error('فشل في حذف الوسوم المحددة');
        },
        onFinish: () => {
            isLoading.value = false;
        }
    });
};

const handleDeleteSingle = (tag: Tag) => {
    if (!confirm(`هل أنت متأكد من حذف ${tag.name}؟ سيتم إزالته من الوصفات المرتبطة.`)) return;

    isLoading.value = true;
    router.delete(route('dashboard.tags.destroy', tag.id), {
        onSuccess: () => {
            toast.success('تم حذف الوسم');
        },
        onError: () => {
            toast.error('فشل في حذف الوسم');
        },
        onFinish: () => {
            isLoading.value = false;
        }
    });
};
</script>

<template>
    <div>
        <div class="flex justify-between items-center mb-4">
            <div v-if="selectedIds.length > 0" class="bg-muted px-4 py-2 rounded-lg flex items-center gap-4">
                <span class="font-medium text-sm">تم تحديد {{ selectedIds.length }}</span>
                <Button size="sm" variant="destructive" @click="handleBulkDelete" :disabled="isLoading">
                    <Trash class="w-4 h-4 mr-1" /> حذف المحدد
                </Button>
            </div>
            <div v-else></div>
            <Button @click="handleOpenCreate">
                <Plus class="w-4 h-4 mr-1" /> إضافة وسم
            </Button>
        </div>

        <div class="rounded-md border">
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead class="w-12">
                            <Checkbox
                                :checked="tags.length > 0 && selectedIds.length === tags.length"
                                @update:checked="handleSelectAll"
                            />
                        </TableHead>
                        <TableHead class="cursor-pointer" @click="emits('sort', 'name')">
                            الاسم
                            <span v-if="sortColumn === 'name'" class="mr-1 inline-block">{{ sortDirection === 'asc' ? '↑' : '↓' }}</span>
                        </TableHead>
                        <TableHead class="cursor-pointer" @click="emits('sort', 'recipes_count')">
                            عدد الوصفات
                            <span v-if="sortColumn === 'recipes_count'" class="mr-1 inline-block">{{ sortDirection === 'asc' ? '↑' : '↓' }}</span>
                        </TableHead>
                        <TableHead>الإجراءات</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    <template v-if="loading">
                        <TableRow v-for="i in 5" :key="i">
                            <TableCell colspan="4" class="h-12 text-center">جاري التحميل...</TableCell>
                        </TableRow>
                    </template>
                    <template v-else-if="tags.length === 0">
                        <TableRow>
                            <TableCell colspan="4" class="h-24 text-center">لا توجد وسوم</TableCell>
                        </TableRow>
                    </template>
                    <template v-else>
                        <TableRow v-for="tag in tags" :key="tag.id">
                            <TableCell>
                                <Checkbox
                                    :checked="selectedIds.includes(tag.id)"
                                    @update:checked="(c) => handleSelectOne(tag.id, c)"
                                />
                            </TableCell>
                            <TableCell class="font-medium">
                                {{ tag.name }}
                            </TableCell>
                            <TableCell>
                                {{ tag.recipes_count }}
                            </TableCell>
                            <TableCell>
                                <DropdownMenu>
                                    <DropdownMenuTrigger asChild>
                                        <Button variant="ghost" size="icon">
                                            <MoreHorizontal class="h-4 w-4" />
                                        </Button>
                                    </DropdownMenuTrigger>
                                    <DropdownMenuContent align="end">
                                        <DropdownMenuItem @click="handleOpenEdit(tag)">
                                            <Edit class="h-4 w-4" /> تعديل
                                        </DropdownMenuItem>
                                        <DropdownMenuItem @click="handleDeleteSingle(tag)" class="text-red-600 focus:text-red-600">
                                            <Trash class="h-4 w-4" /> حذف
                                        </DropdownMenuItem>
                                    </DropdownMenuContent>
                                </DropdownMenu>
                            </TableCell>
                        </TableRow>
                    </template>
                </TableBody>
            </Table>
        </div>

        <PaginationControls
            :current-page="pagination.current_page"
            :total-pages="pagination.last_page"
            :per-page="pagination.per_page"
            :total-items="pagination.total"
            @page-change="(p) => emits('pageChange', p)"
            @per-page-change="(pp) => emits('perPageChange', pp)"
        />

        <Dialog :open="isDialogOpen" @update:open="(v) => isDialogOpen = v">
            <DialogContent class="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>{{ selectedTag ? 'تعديل وسم' : 'إضافة وسم جديد' }}</DialogTitle>
                    <DialogDescription>
                        {{ selectedTag ? 'تعديل اسم الوسم' : 'أدخل اسم الوسم الجديد' }}
                    </DialogDescription>
                </DialogHeader>
                <div class="space-y-4 py-4">
                    <div class="space-y-2">
                        <label class="text-sm font-medium">اسم الوسم</label>
                        <Input
                            v-model="name"
                            placeholder="مثال: نباتي"
                        />
                    </div>
                </div>
                <DialogFooter>
                    <Button variant="outline" @click="isDialogOpen = false">
                        إلغاء
                    </Button>
                    <Button @click="handleSubmit" :disabled="!name.trim() || isLoading">
                        {{ selectedTag ? 'حفظ التعديلات' : 'إنشاء' }}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    </div>
</template>
