// frontend/src/components/admin/reports/ReportsTable.tsx
'use client';

import { useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { PaginationControls } from '@/components/ui/PaginationControls';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import { formatRelativeTime } from '@/lib/utils';
import Link from 'next/link';
import { MoreHorizontal, Trash, ExternalLink, MessageSquare, CheckCircle, XCircle } from 'lucide-react';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Label } from '@/components/ui/label';

interface Report {
    id: number;
    user: { id: number; name: string; email: string; avatar?: string };
    reportable_type: string;
    reportable_id: number;
    reportable?: {
        id: number;
        name: string;
        slug?: string;
    };
    type: string;
    message: string;
    status: string;
    admin_note?: string;
    admin_reply?: string;
    created_at: string;
}

interface ReportsTableProps {
    reports: Report[];
    pagination: {
        current_page: number;
        last_page: number;
        per_page: number;
        total: number;
    };
    onPageChange: (page: number) => void;
    onUpdate: () => void;
    loading: boolean;
}

export function ReportsTable({ reports, pagination, onPageChange, onUpdate, loading }: ReportsTableProps) {
    const { token, user } = useAuth();
    const isAdmin = user?.role === 'admin';
    const [selectedIds, setSelectedIds] = useState<number[]>([]);
    const [isLoading, setIsLoading] = useState(false);

    // Dialogs
    const [detailDialogOpen, setDetailDialogOpen] = useState(false);
    const [selectedReport, setSelectedReport] = useState<Report | null>(null);
    const [navAction, setNavAction] = useState<'pending' | 'fixed' | 'rejected'>('pending');
    const [adminNote, setAdminNote] = useState('');
    const [adminReply, setAdminReply] = useState('');

    const handleSelectAll = (checked: boolean) => {
        if (checked) {
            setSelectedIds(reports.map(r => r.id));
        } else {
            setSelectedIds([]);
        }
    };

    const handleSelectOne = (id: number, checked: boolean) => {
        if (checked) {
            setSelectedIds(prev => [...prev, id]);
        } else {
            setSelectedIds(prev => prev.filter(selectedId => selectedId !== id));
        }
    };

    const handleBulkDelete = async () => {
        if (!token || selectedIds.length === 0) return;
        if (!confirm(`هل أنت متأكد من حذف ${selectedIds.length} بلاغ؟`)) return;

        setIsLoading(true);
        try {
            await api.admin.bulkReportActions(token, selectedIds, 'delete');
            toast.success('تم الحذف بنجاح');
            setSelectedIds([]);
            onUpdate();
        } catch (error) {
            toast.error('حدث خطأ أثناء الحذف');
        } finally {
            setIsLoading(false);
        }
    };

    const handleBulkStatus = async (status: string) => {
        if (!token || selectedIds.length === 0) return;

        setIsLoading(true);
        try {
            await api.admin.bulkReportActions(token, selectedIds, 'status_update', status);
            toast.success('تم تحديث الحالة بنجاح');
            setSelectedIds([]);
            onUpdate();
        } catch (error) {
            toast.error('حدث خطأ أثناء التحديث');
        } finally {
            setIsLoading(false);
        }
    };

    const openDetails = (report: Report) => {
        setSelectedReport(report);
        setNavAction(report.status as any);
        setAdminNote(report.admin_note || '');
        setAdminReply(report.admin_reply || '');
        setDetailDialogOpen(true);
    };

    const handleSaveDetails = async () => {
        if (!token || !selectedReport) return;
        setIsLoading(true);
        try {
            await api.admin.updateReport(token, selectedReport.id, {
                status: navAction,
                admin_note: adminNote,
                admin_reply: adminReply,
            });
            toast.success('تم تحديث البلاغ');
            setDetailDialogOpen(false);
            onUpdate();
        } catch (error) {
            toast.error('فشل التحديث');
        } finally {
            setIsLoading(false);
        }
    };

    const handleDeleteSingle = async (report: Report) => {
        if (!token || !isAdmin) return;
        if (!confirm('هل أنت متأكد من حذف هذا البلاغ؟')) return;
        setIsLoading(true);
        try {
            await api.admin.deleteReport(token, report.id);
            toast.success('تم الحذف');
            onUpdate();
        } catch (error) {
            toast.error('فشل الحذف');
        } finally {
            setIsLoading(false);
        }
    };

    const StatusBadge = ({ status }: { status: string }) => {
        const styles: Record<string, string> = {
            fixed: 'bg-green-100 text-green-800',
            pending: 'bg-amber-100 text-amber-800',
            rejected: 'bg-red-100 text-red-800',
        };
        const labels: Record<string, string> = {
            fixed: 'تم الحل',
            pending: 'قيد المراجعة',
            rejected: 'مرفوض',
        };
        return <Badge className={styles[status]}>{labels[status] || status}</Badge>;
    };

    const getReportableLink = (report: Report) => {
        if (!report.reportable) return <span className="text-muted-foreground">محتوى محذوف</span>;

        const type = report.reportable_type.includes("Recipe") ? "recipes" : "lists";
        const slug = report.reportable.slug || report.reportable.id;

        return (
            <Link href={`/${type}/${slug}`} target="_blank" className="flex items-center gap-1 text-primary hover:underline text-sm">
                {report.reportable.name}
                <ExternalLink className="w-3 h-3" />
            </Link>
        );
    };

    if (loading) return <div className="text-center py-8">جاري التحميل...</div>;

    return (
        <div>
            {selectedIds.length > 0 && (
                <div className="bg-muted p-4 rounded-lg mb-4 flex items-center justify-between">
                    <span className="font-medium text-sm">تم تحديد {selectedIds.length} عنصر</span>
                    <div className="flex gap-2">
                        <Button size="sm" variant="secondary" onClick={() => handleBulkStatus('fixed')} disabled={isLoading}>
                            <CheckCircle className="ml-2 w-4 h-4" />
                            تحديد كـ "تم الحل"
                        </Button>
                        <Button size="sm" variant="secondary" onClick={() => handleBulkStatus('rejected')} disabled={isLoading}>
                            <XCircle className="ml-2 w-4 h-4" />
                            رفض
                        </Button>
                        {isAdmin && (
                            <Button size="sm" variant="destructive" onClick={handleBulkDelete} disabled={isLoading}>
                                <Trash className="ml-2 w-4 h-4" />
                                حذف
                            </Button>
                        )}
                    </div>
                </div>
            )}

            <div className="rounded-md border bg-card">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead className="w-12">
                                <Checkbox
                                    checked={reports.length > 0 && selectedIds.length === reports.length}
                                    onCheckedChange={(c) => handleSelectAll(!!c)}
                                />
                            </TableHead>
                            <TableHead>المرسل</TableHead>
                            <TableHead>المحتوى</TableHead>
                            <TableHead>النوع</TableHead>
                            <TableHead>الرسالة</TableHead>
                            <TableHead>الحالة</TableHead>
                            <TableHead className="text-left">الإجراءات</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {reports.length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={7} className="h-24 text-center">
                                    لا توجد بلاغات
                                </TableCell>
                            </TableRow>
                        ) : (
                            reports.map((report) => (
                                <TableRow key={report.id}>
                                    <TableCell>
                                        <Checkbox
                                            checked={selectedIds.includes(report.id)}
                                            onCheckedChange={(c) => handleSelectOne(report.id, !!c)}
                                        />
                                    </TableCell>
                                    <TableCell>
                                        <div className="flex items-center gap-2">
                                            <Avatar className="w-8 h-8">
                                                <AvatarImage src={report.user.avatar} />
                                                <AvatarFallback>{report.user.name.charAt(0)}</AvatarFallback>
                                            </Avatar>
                                            <div className="flex flex-col">
                                                <span className="text-sm font-medium">{report.user.name}</span>
                                                <span className="text-xs text-muted-foreground">{report.user.email}</span>
                                            </div>
                                        </div>
                                    </TableCell>
                                    <TableCell>
                                        {getReportableLink(report)}
                                    </TableCell>
                                    <TableCell>
                                        <Badge variant="outline">
                                            {report.type === 'content_issue' ? 'مشكلة محتوى' : 'اقتراح'}
                                        </Badge>
                                    </TableCell>
                                    <TableCell className="max-w-[200px]">
                                        <span className="truncate block" title={report.message}>
                                            {report.message}
                                        </span>
                                    </TableCell>
                                    <TableCell>
                                        <StatusBadge status={report.status} />
                                    </TableCell>
                                    <TableCell>
                                        <div className="flex justify-end gap-2">
                                            <Button variant="ghost" size="icon" onClick={() => openDetails(report)}>
                                                <MessageSquare className="w-4 h-4 text-blue-600" />
                                            </Button>
                                            {isAdmin && (
                                                <Button variant="ghost" size="icon" onClick={() => handleDeleteSingle(report)}>
                                                    <Trash className="w-4 h-4 text-red-600" />
                                                </Button>
                                            )}
                                        </div>
                                    </TableCell>
                                </TableRow>
                            ))
                        )}
                    </TableBody>
                </Table>
            </div>

            <PaginationControls
                currentPage={pagination.current_page}
                totalPages={pagination.last_page}
                perPage={pagination.per_page}
                totalItems={pagination.total}
                onPageChange={(p) => onPageChange(p)}
                onPerPageChange={() => { }} // Not implemented in this view
            />

            {/* Details Dialog */}
            <Dialog open={detailDialogOpen} onOpenChange={setDetailDialogOpen}>
                <DialogContent className="max-w-2xl">
                    <DialogHeader>
                        <DialogTitle>تفاصيل البلاغ #{selectedReport?.id}</DialogTitle>
                    </DialogHeader>

                    {selectedReport && (
                        <div className="grid gap-6 py-4">
                            <div className="grid grid-cols-2 gap-4 text-sm">
                                <div>
                                    <Label className="text-muted-foreground">المرسل:</Label>
                                    <div className="font-medium">{selectedReport.user.name}</div>
                                </div>
                                <div>
                                    <Label className="text-muted-foreground">التاريخ:</Label>
                                    <div className="font-medium">{formatRelativeTime(selectedReport.created_at)}</div>
                                </div>
                                <div>
                                    <Label className="text-muted-foreground">النوع:</Label>
                                    <div className="font-medium">{selectedReport.type === 'content_issue' ? 'مشكلة محتوى' : 'اقتراح'}</div>
                                </div>
                                <div>
                                    <Label className="text-muted-foreground">المحتوى:</Label>
                                    <div>{getReportableLink(selectedReport)}</div>
                                </div>
                            </div>

                            <div className="bg-muted p-4 rounded-md">
                                <Label className="mb-2 block">الرسالة:</Label>
                                <p className="text-sm whitespace-pre-wrap">{selectedReport.message}</p>
                            </div>

                            <div className="space-y-4 border-t pt-4">
                                <Label>إجراءات الإدارة</Label>

                                <div className="grid grid-cols-3 gap-2">
                                    <Button
                                        variant={navAction === 'pending' ? "default" : "outline"}
                                        onClick={() => setNavAction('pending')}
                                        size="sm"
                                    >
                                        قيد المراجعة
                                    </Button>
                                    <Button
                                        variant={navAction === 'fixed' ? "default" : "outline"}
                                        onClick={() => setNavAction('fixed')}
                                        size="sm"
                                        className={navAction === 'fixed' ? "bg-green-600 hover:bg-green-700" : ""}
                                    >
                                        تم الحل
                                    </Button>
                                    <Button
                                        variant={navAction === 'rejected' ? "default" : "outline"}
                                        onClick={() => setNavAction('rejected')}
                                        size="sm"
                                        className={navAction === 'rejected' ? "bg-red-600 hover:bg-red-700" : ""}
                                    >
                                        مرفوض
                                    </Button>
                                </div>

                                <div className="space-y-2">
                                    <Label>ملاحظات إدارية (خاصة)</Label>
                                    <Textarea
                                        value={adminNote}
                                        onChange={e => setAdminNote(e.target.value)}
                                        placeholder="ملاحظات للفريق فقط..."
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label>رد على المستخدم (سيظهر للمستخدم)</Label>
                                    <Textarea
                                        value={adminReply}
                                        onChange={e => setAdminReply(e.target.value)}
                                        placeholder="اكتب رداً للمستخدم..."
                                        className="min-h-[100px]"
                                    />
                                </div>
                            </div>
                        </div>
                    )}

                    <DialogFooter>
                        <Button variant="outline" onClick={() => setDetailDialogOpen(false)}>إغلاق</Button>
                        <Button onClick={handleSaveDetails} disabled={isLoading}>حفظ التغييرات</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    );
}

// resources/js/components/admin/reports/ReportsTable.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { router, Link, usePage } from '@inertiajs/vue3';
import { 
    Button, 
    Badge, 
    Checkbox, 
    Table, 
    TableBody, 
    TableCell, 
    TableHead, 
    TableHeader, 
    TableRow,
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
    Dialog,
    DialogContent,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    Textarea,
    PaginationControls,
    Label
} from '@/components/ui';
import { MoreHorizontal, Trash, MessageSquare, CheckCircle, XCircle, ExternalLink } from 'lucide-vue-next';
import { toast } from 'vue-sonner';
import { formatRelativeTime } from '@/lib/utils';
import type { AdminReport, Pagination } from '@/types';

interface Props {
    reports: AdminReport[];
    pagination: Pagination;
    loading?: boolean;
}

const props = defineProps<Props>();

const emits = defineEmits<{
    (e: 'pageChange', page: number): void;
    (e: 'perPageChange', perPage: number): void;
}>();

const { props: pageProps } = usePage();
const isAdmin = computed(() => pageProps.auth?.user?.role === 'admin');
const selectedIds = ref<number[]>([]);
const isLoading = ref(false);

const detailDialogOpen = ref(false);
const selectedReport = ref<AdminReport | null>(null);
const navAction = ref<'pending' | 'fixed' | 'rejected'>('pending');
const adminNote = ref('');
const adminReply = ref('');

const handleSelectAll = (checked: boolean) => {
    if (checked) {
        selectedIds.value = props.reports.map(r => r.id);
    } else {
        selectedIds.value = [];
    }
};

const handleSelectOne = (id: number, checked: boolean) => {
    if (checked) {
        selectedIds.value.push(id);
    } else {
        selectedIds.value = selectedIds.value.filter(selectedId => selectedId !== id);
    }
};

const openDetails = (report: AdminReport) => {
    selectedReport.value = report;
    navAction.value = report.status as any;
    adminNote.value = report.admin_note || '';
    adminReply.value = report.admin_reply || '';
    detailDialogOpen.value = true;
};

const handleSaveDetails = () => {
    if (!selectedReport.value) return;

    isLoading.value = true;
    router.post(route('dashboard.reports.update', selectedReport.value.id), {
        status: navAction.value,
        admin_note: adminNote.value,
        admin_reply: adminReply.value
    }, {
        onSuccess: () => {
            detailDialogOpen.value = false;
            toast.success('تم تحديث البلاغ');
        },
        onError: () => {
            toast.error('فشل تحديث البلاغ');
        },
        onFinish: () => {
            isLoading.value = false;
        }
    });
};

const handleBulkStatus = (status: string) => {
    if (selectedIds.value.length === 0) return;

    isLoading.value = true;
    router.post(route('dashboard.reports.bulk'), {
        ids: selectedIds.value,
        action: 'status_update',
        status
    }, {
        onSuccess: () => {
            selectedIds.value = [];
            toast.success('تم تحديث حالة البلاغات المحددة');
        },
        onError: () => {
            toast.error('فشل تحديث حالة البلاغات');
        },
        onFinish: () => {
            isLoading.value = false;
        }
    });
};

const handleBulkDelete = () => {
    if (selectedIds.value.length === 0) return;
    if (!confirm(`هل أنت متأكد من حذف ${selectedIds.value.length} بلاغ؟`)) return;

    isLoading.value = true;
    router.post(route('dashboard.reports.bulk'), {
        ids: selectedIds.value,
        action: 'delete'
    }, {
        onSuccess: () => {
            selectedIds.value = [];
        },
        onFinish: () => {
            isLoading.value = false;
        }
    });
};

const handleDeleteSingle = (report: AdminReport) => {
    if (!confirm('هل أنت متأكد من حذف هذا البلاغ؟')) return;

    isLoading.value = true;
    router.delete(route('dashboard.reports.destroy', report.id), {
        onSuccess: () => {
            toast.success('تم حذف البلاغ');
        },
        onError: () => {
            toast.error('فشل حذف البلاغ');
        },
        onFinish: () => {
            isLoading.value = false;
        }
    });
};

const getReportableLink = (report: AdminReport) => {
    if (!report.reportable) return 'محتوى محذوف';
    
    // In our backend, reportable_type is the full class name.
    // We should check the type in props or handle it in controller.
    const type = report.reportable_type.includes('Recipe') ? 'recipes' : 'lists';
    const slug = report.reportable.slug || report.reportable.id;
    
    return `/${type}/${slug}`;
};
</script>

<template>
    <div>
        <div v-if="selectedIds.length > 0" class="bg-muted p-4 rounded-lg mb-4 flex items-center justify-between">
            <span class="font-medium text-sm">تم تحديد {{ selectedIds.length }} عنصر</span>
            <div class="flex gap-2">
                <Button size="sm" variant="outline" @click="handleBulkStatus('fixed')" :disabled="isLoading">
                    <CheckCircle class="ml-2 w-4 h-4" /> تم الحل
                </Button>
                <Button size="sm" variant="outline" @click="handleBulkStatus('rejected')" :disabled="isLoading">
                    <XCircle class="ml-2 w-4 h-4" /> رفض
                </Button>
                <Button v-if="isAdmin" size="sm" variant="destructive" @click="handleBulkDelete" :disabled="isLoading">
                    <Trash class="ml-2 w-4 h-4" /> حذف
                </Button>
            </div>
        </div>

        <div class="rounded-md border">
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead class="w-12">
                            <Checkbox
                                :checked="reports.length > 0 && selectedIds.length === reports.length"
                                @update:checked="handleSelectAll"
                            />
                        </TableHead>
                        <TableHead>المرسل</TableHead>
                        <TableHead>المحتوى</TableHead>
                        <TableHead>النوع</TableHead>
                        <TableHead>الحالة</TableHead>
                        <TableHead>تاريخ البلاغ</TableHead>
                        <TableHead class="text-left">الإجراءات</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    <template v-if="loading">
                        <TableRow v-for="i in 5" :key="i">
                            <TableCell colspan="7" class="h-12 text-center">جاري التحميل...</TableCell>
                        </TableRow>
                    </template>
                    <template v-else-if="reports.length === 0">
                        <TableRow>
                            <TableCell colspan="7" class="h-24 text-center">لا توجد بلاغات</TableCell>
                        </TableRow>
                    </template>
                    <template v-else>
                        <TableRow v-for="report in reports" :key="report.id">
                            <TableCell>
                                <Checkbox
                                    :checked="selectedIds.includes(report.id)"
                                    @update:checked="(c) => handleSelectOne(report.id, c)"
                                />
                            </TableCell>
                            <TableCell>
                                <div class="flex items-center gap-2">
                                    <div v-if="report.user.avatar" class="w-8 h-8 rounded-full overflow-hidden">
                                        <img :src="report.user.avatar" class="w-full h-full object-cover" />
                                    </div>
                                    <div v-else class="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-xs">👤</div>
                                    <div class="flex flex-col">
                                        <span class="text-sm font-medium">{{ report.user.name }}</span>
                                        <span class="text-xs text-muted-foreground">{{ report.user.email }}</span>
                                    </div>
                                </div>
                            </TableCell>
                            <TableCell>
                                <a v-if="report.reportable" :href="getReportableLink(report)" target="_blank" class="flex items-center gap-1 text-primary hover:underline text-sm">
                                    {{ report.reportable.name }}
                                    <ExternalLink class="w-3 h-3" />
                                </a>
                                <span v-else class="text-muted-foreground text-sm">محتوى محذوف</span>
                            </TableCell>
                            <TableCell>
                                <Badge variant="outline" class="text-[10px]">
                                    {{ report.type === 'content_issue' ? 'مشكلة محتوى' : 'اقتراح' }}
                                </Badge>
                            </TableCell>
                            <TableCell>
                                <Badge :class="[
                                    report.status === 'fixed' ? 'bg-green-100 text-green-800' :
                                    report.status === 'pending' ? 'bg-amber-100 text-amber-800' :
                                    'bg-red-100 text-red-800'
                                ]" class="text-[10px]">
                                    {{ report.status === 'fixed' ? 'تم الحل' : report.status === 'pending' ? 'مراجعة' : 'مرفوض' }}
                                </Badge>
                            </TableCell>
                            <TableCell>
                                <span class="text-xs text-muted-foreground">{{ formatRelativeTime(report.created_at) }}</span>
                            </TableCell>
                            <TableCell>
                                <div class="flex justify-end gap-2">
                                    <Button variant="ghost" size="icon" @click="openDetails(report)">
                                        <MessageSquare class="w-4 h-4 text-blue-600" />
                                    </Button>
                                    <DropdownMenu>
                                        <DropdownMenuTrigger asChild>
                                            <Button variant="ghost" size="icon">
                                                <MoreHorizontal class="h-4 w-4" />
                                            </Button>
                                        </DropdownMenuTrigger>
                                        <DropdownMenuContent align="end">
                                            <DropdownMenuItem @click="handleDeleteSingle(report)" class="text-red-600 focus:text-red-600">
                                                <Trash class="h-4 w-4" /> حذف
                                            </DropdownMenuItem>
                                        </DropdownMenuContent>
                                    </DropdownMenu>
                                </div>
                            </TableCell>
                        </TableRow>
                    </template>
                </TableBody>
            </Table>
        </div>

        <PaginationControls
            :current-page="pagination.current_page"
            :total-pages="pagination.last_page"
            :per-page="pagination.per_page"
            :total-items="pagination.total"
            @page-change="(p) => emits('pageChange', p)"
            @per-page-change="(pp) => emits('perPageChange', pp)"
        />

        <Dialog :open="detailDialogOpen" @update:open="(v) => detailDialogOpen = v">
            <DialogContent class="max-w-2xl">
                <DialogHeader>
                    <DialogTitle>تفاصيل البلاغ #{{ selectedReport?.id }}</DialogTitle>
                </DialogHeader>

                <div v-if="selectedReport" class="grid gap-6 py-4">
                    <div class="grid grid-cols-2 gap-4 text-sm">
                        <div>
                            <Label class="text-muted-foreground">المرسل:</Label>
                            <div class="font-medium">{{ selectedReport.user.name }}</div>
                        </div>
                        <div>
                            <Label class="text-muted-foreground">التاريخ:</Label>
                            <div class="font-medium">{{ formatRelativeTime(selectedReport.created_at) }}</div>
                        </div>
                        <div>
                            <Label class="text-muted-foreground">النوع:</Label>
                            <div class="font-medium">{{ selectedReport.type === 'content_issue' ? 'مشكلة محتوى' : 'اقتراح' }}</div>
                        </div>
                        <div>
                            <Label class="text-muted-foreground">المحتوى:</Label>
                            <div v-if="selectedReport.reportable">
                                <a :href="getReportableLink(selectedReport)" target="_blank" class="text-primary hover:underline">{{ selectedReport.reportable.name }}</a>
                            </div>
                            <div v-else class="text-muted-foreground">محتوى محذوف</div>
                        </div>
                    </div>

                    <div class="bg-muted p-4 rounded-md">
                        <Label class="mb-2 block">الرسالة:</Label>
                        <p class="text-sm whitespace-pre-wrap">{{ selectedReport.message }}</p>
                    </div>

                    <div class="space-y-4 border-t pt-4">
                        <Label>إجراءات الإدارة</Label>

                        <div class="grid grid-cols-3 gap-2">
                            <Button
                                :variant="navAction === 'pending' ? 'default' : 'outline'"
                                @click="navAction = 'pending'"
                                size="sm"
                            >
                                قيد المراجعة
                            </Button>
                            <Button
                                :variant="navAction === 'fixed' ? 'default' : 'outline'"
                                @click="navAction = 'fixed'"
                                size="sm"
                                :class="navAction === 'fixed' ? 'bg-green-600 hover:bg-green-700' : ''"
                            >
                                تم الحل
                            </Button>
                            <Button
                                :variant="navAction === 'rejected' ? 'default' : 'outline'"
                                @click="navAction = 'rejected'"
                                size="sm"
                                :class="navAction === 'rejected' ? 'bg-red-600 hover:bg-red-700' : ''"
                            >
                                مرفوض
                            </Button>
                        </div>

                        <div class="space-y-2">
                            <Label>ملاحظات إدارية (خاصة)</Label>
                            <Textarea
                                v-model="adminNote"
                                placeholder="ملاحظات للفريق فقط..."
                            />
                        </div>

                        <div class="space-y-2">
                            <Label>رد على المستخدم (سيظهر للمستخدم)</Label>
                            <Textarea
                                v-model="adminReply"
                                placeholder="اكتب رداً للمستخدم..."
                                class="min-h-[100px]"
                            />
                        </div>
                    </div>
                </div>

                <DialogFooter>
                    <Button variant="outline" @click="detailDialogOpen = false">إغلاق</Button>
                    <Button @click="handleSaveDetails" :disabled="isLoading">حفظ التغييرات</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    </div>
</template>
