// frontend/src/app/dashboard/lists/page.tsx
'use client';

import { useEffect, useState, useCallback, Suspense } from 'react';
import { useAuth } from '@/lib/auth-context';
import { api } from '@/lib/api';
import { UnifiedListTable } from '@/components/admin/UnifiedListTable';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useSearchParams, useRouter, usePathname } from 'next/navigation';
import { Search, Filter } from 'lucide-react';
import { Pagination } from '@/types';
import {
    DropdownMenu,
    DropdownMenuCheckboxItem,
    DropdownMenuContent,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

function ListsContent() {
    const { token } = useAuth();
    const router = useRouter();
    const pathname = usePathname();
    const searchParams = useSearchParams();

    const [lists, setLists] = useState<any[]>([]);
    const [meta, setMeta] = useState<Pagination>({ current_page: 1, last_page: 1, total: 0, per_page: 20 });
    const [loading, setLoading] = useState(true);

    // Filter states
    const [searchQuery, setSearchQuery] = useState(searchParams.get('search') || '');
    const [statusFilter, setStatusFilter] = useState<string[]>(
        searchParams.get('status')?.split(',') || []
    );

    // Sort states
    const [sortColumn, setSortColumn] = useState(searchParams.get('sort_by') || 'updated_at');
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>(
        (searchParams.get('sort_dir') as 'asc' | 'desc') || 'desc'
    );

    const fetchLists = useCallback(async () => {
        if (!token) return;
        setLoading(true);
        try {
            const page = Number(searchParams.get('page')) || 1;
            const perPage = Number(searchParams.get('per_page')) || 20;

            const response = await api.admin.getLists(token, {
                page,
                per_page: perPage,
                search: searchQuery,
                status: statusFilter.length > 0 ? statusFilter.join(',') : undefined,
                sort_by: sortColumn,
                sort_dir: sortDirection
            }) as { data: any[], current_page: number, last_page: number, total: number, per_page: number };

            // Map pagination data
            setLists(response.data);
            setMeta({
                current_page: response.current_page,
                last_page: response.last_page,
                total: response.total,
                per_page: response.per_page
            });
        } catch (error) {
            console.error('Failed to fetch lists:', error);
        } finally {
            setLoading(false);
        }
    }, [token, searchParams, searchQuery, statusFilter, sortColumn, sortDirection]);

    useEffect(() => {
        const timer = setTimeout(() => {
            fetchLists();
        }, 300);
        return () => clearTimeout(timer);
    }, [fetchLists]);

    const updateUrl = (updates: Record<string, string | null>) => {
        const params = new URLSearchParams(searchParams.toString());
        Object.entries(updates).forEach(([key, value]) => {
            if (value === null) {
                params.delete(key);
            } else {
                params.set(key, value);
            }
        });
        router.push(`${pathname}?${params.toString()}`);
    };

    const handleSearch = (e: React.FormEvent) => {
        e.preventDefault();
        updateUrl({ search: searchQuery, page: '1' });
    };

    const handleStatusChange = (status: string, checked: boolean) => {
        let newStatuses;
        if (checked) {
            newStatuses = [...statusFilter, status];
        } else {
            newStatuses = statusFilter.filter(s => s !== status);
        }
        setStatusFilter(newStatuses);
        updateUrl({
            status: newStatuses.length > 0 ? newStatuses.join(',') : null,
            page: '1'
        });
    };

    const handleSort = (column: string) => {
        const newDirection = sortColumn === column && sortDirection === 'desc' ? 'asc' : 'desc';
        setSortColumn(column);
        setSortDirection(newDirection);
        updateUrl({ sort_by: column, sort_dir: newDirection });
    };

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <h2 className="text-2xl font-bold tracking-tight">إدارة القوائم</h2>

                <div className="flex items-center gap-2 w-full sm:w-auto">
                    <form onSubmit={handleSearch} className="relative flex-1 sm:w-64">
                        <Search className="absolute right-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                        <Input
                            type="search"
                            placeholder="بحث عن قائمة..."
                            className="pr-9"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                        />
                    </form>

                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button variant="outline" size="icon" className={statusFilter.length > 0 ? 'border-primary text-primary' : ''}>
                                <Filter className="h-4 w-4" />
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="w-56">
                            <DropdownMenuLabel>تصفية حسب الحالة</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            <DropdownMenuCheckboxItem
                                checked={statusFilter.includes('review')}
                                onCheckedChange={(checked) => handleStatusChange('review', checked)}
                            >
                                بانتظار الموافقة
                            </DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem
                                checked={statusFilter.includes('approved')}
                                onCheckedChange={(checked) => handleStatusChange('approved', checked)}
                            >
                                منشورة
                            </DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem
                                checked={statusFilter.includes('rejected')}
                                onCheckedChange={(checked) => handleStatusChange('rejected', checked)}
                            >
                                مرفوضة
                            </DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem
                                checked={statusFilter.includes('private')}
                                onCheckedChange={(checked) => handleStatusChange('private', checked)}
                            >
                                خاصة
                            </DropdownMenuCheckboxItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </div>
            </div>

            <UnifiedListTable
                lists={lists}
                onUpdate={fetchLists}
                pagination={meta}
                onPageChange={(page) => updateUrl({ page: String(page) })}
                onPerPageChange={(perPage) => updateUrl({ per_page: String(perPage), page: '1' })}
                loading={loading}
                sortColumn={sortColumn}
                sortDirection={sortDirection}
                onSort={handleSort}
            />
        </div>
    );
}

export default function ListsPage() {
    return (
        <Suspense fallback={<div>جاري التحميل...</div>}>
            <ListsContent />
        </Suspense>
    );
}

// resources/js/Pages/Dashboard/Lists/Index.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { Head, router } from '@inertiajs/vue3';
import DashboardLayout from '@/Layouts/DashboardLayout.vue';
import UnifiedListTable from '@/components/admin/UnifiedListTable.vue';
import { 
    Input, 
    Button,
    DropdownMenu,
    DropdownMenuCheckboxItem,
    DropdownMenuContent,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger
} from '@/components/ui';
import { Search, Filter } from 'lucide-vue-next';
import { useDebounceFn } from '@vueuse/core';

interface List {
    id: number;
    name: string;
    description: string;
    user: { id: number; name: string; avatar?: string };
    recipes_count: number;
    updated_at: string;
    status: string;
    is_public: boolean;
}

interface Pagination {
    current_page: number;
    last_page: number;
    total: number;
    per_page: number;
}

interface Props {
    lists: {
        data: List[];
        current_page: number;
        last_page: number;
        total: number;
        per_page: number;
    };
    filters: {
        search?: string;
        status?: string;
        sort_by?: string;
        sort_dir?: string;
    };
}

const props = defineProps<Props>();

const searchQuery = ref(props.filters.search || '');
const statusFilter = ref<string[]>(props.filters.status ? props.filters.status.split(',') : []);

const debouncedSearch = useDebounceFn(() => {
    updateUrl();
}, 500);

watch(searchQuery, () => {
    debouncedSearch();
});

const updateUrl = () => {
    router.get(route('dashboard.lists'), {
        search: searchQuery.value || undefined,
        status: statusFilter.value.length > 0 ? statusFilter.value.join(',') : undefined,
        sort_by: props.filters.sort_by,
        sort_dir: props.filters.sort_dir,
        per_page: props.lists.per_page,
        page: 1, // Reset to first page on filter change
    }, {
        preserveState: true,
        replace: true,
        only: ['lists', 'filters'],
    });
};

const handleStatusChange = (status: string, checked: boolean) => {
    if (checked) {
        statusFilter.value.push(status);
    } else {
        statusFilter.value = statusFilter.value.filter(s => s !== status);
    }
    updateUrl();
};

const handleSort = (column: string) => {
    const isCurrent = props.filters.sort_by === column;
    const direction = isCurrent && props.filters.sort_dir === 'desc' ? 'asc' : 'desc';
    
    router.get(route('dashboard.lists'), {
        ...props.filters,
        sort_by: column,
        sort_dir: direction,
        page: props.lists.current_page,
    }, {
        preserveState: true,
        replace: true,
        only: ['lists', 'filters'],
    });
};

const handlePageChange = (page: number) => {
    router.get(route('dashboard.lists'), {
        ...props.filters,
        page,
        per_page: props.lists.per_page,
    }, {
        preserveState: true,
        only: ['lists'],
    });
};

const handlePerPageChange = (perPage: number) => {
    router.get(route('dashboard.lists'), {
        ...props.filters,
        per_page: perPage,
        page: 1,
    }, {
        preserveState: true,
        only: ['lists'],
    });
};
</script>

<template>
    <Head title="إدارة القوائم" />

    <DashboardLayout>
        <div class="space-y-6">
            <div class="flex flex-col sm:flex-row-reverse justify-between items-start sm:items-center gap-4">
                <h2 class="text-2xl font-bold tracking-tight text-right w-full sm:w-auto">إدارة القوائم</h2>

                <div class="flex items-center gap-2 w-full sm:w-auto">
                    <div class="relative flex-1 sm:w-64">
                        <Search class="absolute right-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                        <Input
                            type="search"
                            placeholder="بحث عن قائمة..."
                            class="pr-9 text-right"
                            v-model="searchQuery"
                        />
                    </div>

                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button variant="outline" size="icon" :class="statusFilter.length > 0 ? 'border-primary text-primary' : ''">
                                <Filter class="h-4 w-4" />
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" class="w-56 text-right">
                            <DropdownMenuLabel>تصفية حسب الحالة</DropdownMenuLabel>
                            <DropdownMenuSeparator />
                            <DropdownMenuCheckboxItem
                                :checked="statusFilter.includes('review')"
                                @update:checked="(c) => handleStatusChange('review', c)"
                            >
                                بانتظار الموافقة
                            </DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem
                                :checked="statusFilter.includes('approved')"
                                @update:checked="(c) => handleStatusChange('approved', c)"
                            >
                                منشورة
                            </DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem
                                :checked="statusFilter.includes('rejected')"
                                @update:checked="(c) => handleStatusChange('rejected', c)"
                            >
                                مرفوضة
                            </DropdownMenuCheckboxItem>
                            <DropdownMenuCheckboxItem
                                :checked="statusFilter.includes('private')"
                                @update:checked="(c) => handleStatusChange('private', c)"
                            >
                                خاصة
                            </DropdownMenuCheckboxItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </div>
            </div>

            <UnifiedListTable
                :lists="lists.data"
                :pagination="{
                    current_page: lists.current_page,
                    last_page: lists.last_page,
                    total: lists.total,
                    per_page: lists.per_page
                }"
                :sort-column="filters.sort_by || 'updated_at'"
                :sort-direction="(filters.sort_dir as 'asc' | 'desc') || 'desc'"
                @sort="handleSort"
                @page-change="handlePageChange"
                @per-page-change="handlePerPageChange"
            />
        </div>
    </DashboardLayout>
</template>
