// resources/js/Pages/Dashboard/Tags/Index.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { Head, router } from '@inertiajs/vue3';
import DashboardLayout from '@/Layouts/DashboardLayout.vue';
import UnifiedTagTable from '@/components/admin/UnifiedTagTable.vue';
import { Input } from '@/components/ui';
import { Search } from 'lucide-vue-next';
import type { Tag, Pagination } from '@/types';
import { useDebounceFn } from '@vueuse/core';

interface Props {
    tags: {
        data: Tag[];
        links: any[];
    } & Pagination;
    filters: {
        search?: string;
        sort_by?: string;
        sort_dir?: 'asc' | 'desc';
        per_page?: number;
    };
}

const props = defineProps<Props>();

const searchQuery = ref(props.filters.search || '');

const updateUrl = (updates: Record<string, any>) => {
    router.get(route('dashboard.tags'), {
        ...props.filters,
        ...updates,
    }, {
        preserveState: true,
        preserveScroll: true,
        replace: true
    });
};

const debouncedSearch = useDebounceFn(() => {
    updateUrl({ search: searchQuery.value, page: 1 });
}, 500);

watch(searchQuery, () => {
    debouncedSearch();
});

const handleSort = (column: string) => {
    const direction = props.filters.sort_by === column && props.filters.sort_dir === 'asc' ? 'desc' : 'asc';
    updateUrl({ sort_by: column, sort_dir: direction });
};

const handlePageChange = (page: number) => {
    updateUrl({ page });
};

const handlePerPageChange = (perPage: number) => {
    updateUrl({ per_page: perPage, page: 1 });
};
</script>

<template>
    <Head title="إدارة الوسوم" />

    <DashboardLayout>
        <div class="space-y-6">
            <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <h2 class="text-2xl font-bold tracking-tight">إدارة الوسوم</h2>

                <div class="flex items-center gap-2 w-full sm:w-auto">
                    <div class="relative flex-1 sm:w-64">
                        <Search class="absolute right-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                        <Input
                            type="search"
                            placeholder="بحث عن وسم..."
                            class="pr-9"
                            v-model="searchQuery"
                        />
                    </div>
                </div>
            </div>

            <UnifiedTagTable
                :tags="tags.data"
                :pagination="tags"
                :sort-column="filters.sort_by || 'recipes_count'"
                :sort-direction="filters.sort_dir || 'desc'"
                @sort="handleSort"
                @page-change="handlePageChange"
                @per-page-change="handlePerPageChange"
            />
        </div>
    </DashboardLayout>
</template>

// frontend/src/app/dashboard/tags/page.tsx
'use client';

import { useEffect, useState, useCallback, Suspense } from 'react';
import { useAuth } from '@/lib/auth-context';
import { api } from '@/lib/api';
import { UnifiedTagTable } from '@/components/admin/UnifiedTagTable';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useSearchParams, useRouter, usePathname } from 'next/navigation';
import { Search } from 'lucide-react';
import { Pagination } from '@/types';

// Define Tag type locally or import if available
interface Tag {
    id: number;
    name: string;
    recipes_count: number;
}

function TagsContent() {
    const { token, user } = useAuth();
    const router = useRouter();
    const pathname = usePathname();
    const searchParams = useSearchParams();

    const [tags, setTags] = useState<Tag[]>([]);
    const [meta, setMeta] = useState<Pagination>({ current_page: 1, last_page: 1, total: 0, per_page: 20 });
    const [loading, setLoading] = useState(true);

    // Filter states
    const [searchQuery, setSearchQuery] = useState(searchParams.get('search') || '');

    // Sort states
    const [sortColumn, setSortColumn] = useState(searchParams.get('sort_by') || 'recipes_count');
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>(
        (searchParams.get('sort_dir') as 'asc' | 'desc') || 'desc'
    );

    const fetchTags = useCallback(async () => {
        if (!token) return;
        setLoading(true);
        try {
            const page = Number(searchParams.get('page')) || 1;
            const perPage = Number(searchParams.get('per_page')) || 20;

            const response = await api.admin.getAdminTags(token, {
                page,
                per_page: perPage,
                search: searchQuery,
                sort_by: sortColumn,
                sort_dir: sortDirection
            }) as { tags: Tag[], pagination: Pagination };

            setTags(response.tags);
            setMeta(response.pagination);
        } catch (error) {
            console.error('Failed to fetch tags:', error);
        } finally {
            setLoading(false);
        }
    }, [token, searchParams, searchQuery, sortColumn, sortDirection]);

    useEffect(() => {
        const timer = setTimeout(() => {
            fetchTags();
        }, 300);
        return () => clearTimeout(timer);
    }, [fetchTags]);

    const updateUrl = (updates: Record<string, string | null>) => {
        const params = new URLSearchParams(searchParams.toString());
        Object.entries(updates).forEach(([key, value]) => {
            if (value === null) {
                params.delete(key);
            } else {
                params.set(key, value);
            }
        });
        router.push(`${pathname}?${params.toString()}`);
    };

    const handleSearch = (e: React.FormEvent) => {
        e.preventDefault();
        updateUrl({ search: searchQuery, page: '1' });
    };

    const handleSort = (column: string) => {
        const newDirection = sortColumn === column && sortDirection === 'desc' ? 'asc' : 'desc';
        setSortColumn(column);
        setSortDirection(newDirection);
        updateUrl({ sort_by: column, sort_dir: newDirection });
    };

    if (user && user.role !== 'admin' && user.role !== 'moderator') {
        // Moderators can manage tags per API routes usually, but let's check role access in task requirements
        // "Tags Dashboard accessible by admin and moderator"
        return <div className="p-8 text-center text-red-500">غير مصرح لك بالوصول إلى هذه الصفحة</div>;
    }

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <h2 className="text-2xl font-bold tracking-tight">إدارة الوسوم</h2>

                <div className="flex items-center gap-2 w-full sm:w-auto">
                    <form onSubmit={handleSearch} className="relative flex-1 sm:w-64">
                        <Search className="absolute right-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                        <Input
                            type="search"
                            placeholder="بحث عن وسم..."
                            className="pr-9"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                        />
                    </form>
                </div>
            </div>

            <UnifiedTagTable
                tags={tags}
                onUpdate={fetchTags}
                pagination={meta}
                onPageChange={(page) => updateUrl({ page: String(page) })}
                onPerPageChange={(perPage) => updateUrl({ per_page: String(perPage), page: '1' })}
                loading={loading}
                sortColumn={sortColumn}
                sortDirection={sortDirection}
                onSort={handleSort}
            />
        </div>
    );
}

export default function TagsPage() {
    return (
        <Suspense fallback={<div>جاري التحميل...</div>}>
            <TagsContent />
        </Suspense>
    );
}
